name: nftree-eco-backend
version: 0.0.1-alpha
synopsis: A servant backend for nftree.eco
description: See README at <https://github.com/chiroptical/nftree-eco-backend>
maintainer: Barry
github: chiroptical/nftree-eco-backend

ghc-options: -Wall

default-extensions:
- DataKinds
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeOperators

dependencies:
- base >=4.11 && < 5
- bytestring
- cassava
- cryptonite
- esqueleto
- monad-logger
- mtl
- password
- persistent
- persistent-sqlite
- quickcheck-instances
- QuickCheck
- random
- resourcet
- servant
- servant-auth-server
- servant-server
- text
- time
- transformers
- unliftio
- utf8-string
- vector
- wai-cors
- wai-logger
- warp

library:
  source-dirs: src
  dependencies:
    - aeson

executables:
  server:
    main: Main.hs
    source-dirs: app
    dependencies:
      - nftree-eco-backend

  seed:
    main: Main.hs
    source-dirs: seed
    dependencies:
      - nftree-eco-backend

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - hedgehog
      - nftree-eco-backend
